leftnav:
- identifier: 2e139d12-71d2-1d5c-aeea-b5f296fc40d9
  name: Syllabus
  url: /pages/syllabus
  weight: 10
- identifier: external-f8e095a3aa964872bf86f9857c787477
  name: Quantum Information Science II, Part 1
  url: https://openlearninglibrary.mit.edu/courses/course-v1:MITx+8.371.1x+2T2018/about
  weight: 1000
- identifier: external-27fb043d84aa4a5291c506f8aa6fd526
  name: Quantum Information Science II, Part 2
  url: https://openlearninglibrary.mit.edu/courses/course-v1:MITx+8.371.2x+1T2018/about
  weight: 1010
- identifier: external-4e862641fe3a44a3b0940aa76a49016f
  name: Quantum Information Science II, Part 3
  url: https://openlearninglibrary.mit.edu/courses/course-v1:MITx+8.371.3x+1T2018/about
  weight: 1020
